name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker Worker base image
      uses: pmorelli92/github-container-registry-build-push@2.1.0
      with:
        github-push-secret: ${{secrets.GITHUB_TOKEN}}
        docker-image-name: nevvisk-trophy-bot
        dockerfile-path: TrophyBot/Dockerfile
        build-context: .
